env: "info" # levels of logging: "debug"/"info"/"json"

ctx_timeout: 8s

tgBothost: "api.telegram.org"

psql_storage:
  db_driver: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "sups"
  user: "postgres"
  sslmode: "disable"

api_server:
  address: "0.0.0.0:8008"
  timeout: 4s
  idle_timeout: 600s

frontend:
  domains: ["http://localhost:80"]